# Generated by Django 5.2.7 on 2025-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_lang_pro_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4, unique=True)),
                ('image', models.ImageField(upload_to='images/letters/')),
                ('audio', models.FileField(upload_to='audio/letters/')),
            ],
        ),
    ]
