# Generated by Django 5.2.7 on 2025-10-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_lang_pro_app', '0002_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='image',
            field=models.ImageField(null=True, upload_to='images/letters/'),
        ),
    ]
