# Generated by Django 5.2.7 on 2025-10-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_lang_pro_app', '0005_alter_letter_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12, unique=True)),
                ('description', models.TextField()),
                ('audio', models.FileField(upload_to='audio/numbers/')),
            ],
        ),
        migrations.AlterField(
            model_name='letter',
            name='image',
            field=models.ImageField(default='images/letters/default.jpg', upload_to='images/letters/'),
        ),
    ]
