# Generated by Django 5.2.7 on 2025-11-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg_lang_pro_app', '0006_numbers_alter_letter_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson',
            new_name='Lessons',
        ),
        migrations.RenameModel(
            old_name='Letter',
            new_name='Letters',
        ),
    ]
